spring:
  application:
    name: orbit-flow
  profiles:
    active: dev

  jackson:
    default-property-inclusion: non_null

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      timeout: 2000ms

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when-authorized